apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:kube-proxy
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - nodes
      - configmaps
    verbs:
      - list
      - watch
      - get
  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs:
      - list
      - watch
      - get