apiVersion: v1
data:
  config.conf: |
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    kind: KubeProxyConfiguration
    clusterCIDR: 10.42.0.0/16
    mode: iptables
    clientConnection:
      kubeconfig: /var/lib/kubeconfig
    iptables:
      masqueradeAll: true
    conntrack:
      maxPerCore: 0
    featureGates:
      AllAlpha: false
kind: ConfigMap
metadata:
  labels:
    app: kube-proxy
    k8s-app: kube-proxy
  name: kube-proxy
  namespace: kube-proxy