apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-proxy
  namespace: kube-proxy
spec:
  selector:
    matchLabels:
      k8s-app: kube-proxy
  template:
    metadata:
      labels:
        k8s-app: kube-proxy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      serviceAccountName: kube-proxy  # Reference the Service Account here
      containers:
        - name: kube-proxy
          image: kube-proxy
          command:
            - /usr/bin/kube-proxy
            - --config=/var/lib/kube-proxy/config.conf
          volumeMounts:
            - name: config
              mountPath: /var/lib/kube-proxy/
              readOnly: true
            - name: kubeconfig
              mountPath: /var/lib/kubeconfig
              readOnly: true
          securityContext:
            privileged: true
      hostNetwork: true  # Allows the pod to use the host network
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - effect: NoSchedule
          operator: Exists
      volumes:
        - name: config
          configMap:
            name: kube-proxy
        - hostPath:
            path: /var/lib/microshift/resources/kubeadmin/kubeconfig
            type: FileOrCreate
          name: kubeconfig