name: linters
description: Presubmit static checks and linting

on:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Run ShellCheck
        run: |
          make _shellcheck

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Run Hadolint
        run: |
          make _hadolint
