name: presubmit-pr-check
description: Presubmit Pull Request Verification

on:
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Run ShellCheck
        run: |
          make _shellcheck

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Run Hadolint
        run: |
          make _hadolint

  centos9-bootc-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Detect OKD version tag
        id: detect-okd-version
        uses: ./.github/actions/okd-version

      - name: Run the build action
        uses: ./.github/actions/build
        with:
          ushift-branch: main
          okd-version-tag: ${{ steps.detect-okd-version.outputs.okd-version-tag }}
          bootc-image-url: quay.io/centos-bootc/centos-bootc
          bootc-image-tag: stream9
          build: bootc-image

  centos10-bootc-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Detect OKD version tag
        id: detect-okd-version
        uses: ./.github/actions/okd-version

      - name: Run the build action
        uses: ./.github/actions/build
        with:
          ushift-branch: main
          okd-version-tag: ${{ steps.detect-okd-version.outputs.okd-version-tag }}
          bootc-image-url: quay.io/centos-bootc/centos-bootc
          bootc-image-tag: stream10
          build: bootc-image

  fedora-bootc-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Detect OKD version tag
        id: detect-okd-version
        uses: ./.github/actions/okd-version

      - name: Run the build action
        uses: ./.github/actions/build
        with:
          ushift-branch: main
          okd-version-tag: ${{ steps.detect-okd-version.outputs.okd-version-tag }}
          bootc-image-url: registry.fedoraproject.org/fedora-bootc
          bootc-image-tag: latest
          build: bootc-image

  isolated-network-kindnet-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Detect OKD version tag
        id: detect-okd-version
        uses: ./.github/actions/okd-version

      - name: Run the build action
        uses: ./.github/actions/build
        with:
          ushift-branch: main
          okd-version-tag: ${{ steps.detect-okd-version.outputs.okd-version-tag }}
          isolated-network: 1
          ovnk-networking: 0
          build: bootc-image

  isolated-network-ovnk-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Detect OKD version tag
        id: detect-okd-version
        uses: ./.github/actions/okd-version

      - name: Run the build action
        uses: ./.github/actions/build
        with:
          ushift-branch: main
          okd-version-tag: ${{ steps.detect-okd-version.outputs.okd-version-tag }}
          isolated-network: 1
          ovnk-networking: 1
          build: bootc-image

  quick-start-and-clean:
    runs-on: ubuntu-latest
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Run the quick start script
        shell: bash
        run: |
          set -x
          cat ./src/quickstart.sh | sudo bash -x

          # Wait until the MicroShift service is ready and healthy
          make run-ready
          make run-healthy

      - name: Run the quick clean script
        shell: bash
        run: |
          set -x
          cat ./src/quickclean.sh | sudo bash -x

          # Verify the container and its image are removed
          sudo podman ps -a  | grep microshift-okd && exit 1
          sudo podman images | grep microshift-okd && exit 1

          # Verify the LVM volume group and backing storage are removed
          sudo vgs | grep myvg1 && exit 1
          if [ -e /var/lib/microshift-okd ]; then
            ls -la /var/lib/microshift-okd/
            exit 1
          fi
