name: Release MicroShift RPMs and Container Images
description: Workflow to build and release MicroShift RPMs and container images

on:
  workflow_dispatch:
    inputs:
      ushift-branch:
        default: "main"
        description: MicroShift branch from https://github.com/openshift/microshift/branches
        type: string
      okd-version-tag:
        default: "4.19.0-okd-scos.19"
        description: OKD version tag from https://quay.io/repository/okd/scos-release?tab=tags
        type: string
      build:
        type: choice
        description: Types of artifacts to build
        default: all
        options:
        - all
        - rpms
        - bootc-image

jobs:
  build:
    strategy:
      matrix:
        # The ARM runner is disabled because OKD images for ARM are not available.
        # See USHIFT-5570
        runners: [ubuntu-24.04]
    name: Build MicroShift upstream
    runs-on: ${{ matrix.runners }}
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Run the build action
        uses: ./.github/actions/build
        with:
          ushift-branch: ${{ inputs.ushift-branch }}
          okd-version-tag: ${{ inputs.okd-version-tag }}
          build: ${{ inputs.build }}

        # The release process consumes the RPMs and the container image
        # prepared by the build action.
      - name: Prepare the RPM archives
        if: contains(fromJSON('["all", "rpms"]'), inputs.build)
        shell: bash
        run : |
          # Archive sources separately from the RPMs
          sudo mv /mnt/rpms/srpms /mnt/srpms
          cd /mnt/srpms
          sudo tar zcvf /mnt/release/microshift-src.tgz .

          cd /mnt/rpms
          sudo tar zcvf /mnt/release/microshift-rpms-$(uname -m).tgz .

      - name: Release RPMs
        if: contains(fromJSON('["all", "rpms"]'), inputs.build)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.ushift-branch }}-${{ inputs.okd-version-tag }}
          files: |
            /mnt/release/microshift-rpms-*.tgz
            /mnt/release/microshift-src.tgz
          overwrite_files: true

      - name: Login to GitHub Container Registry
        if: contains(fromJSON('["all", "bootc-image"]'), inputs.build)
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          auth_file_path: /tmp/ghcr-auth.json

      - name: Publish Bootc image
        if: contains(fromJSON('["all", "bootc-image"]'), inputs.build)
        shell: bash
        run: |
          sudo podman tag microshift-okd \
            ghcr.io/${{ github.repository }}:${{ inputs.ushift-branch }}-${{ inputs.okd-version-tag }} \
            ghcr.io/${{ github.repository }}:latest
          sudo podman push --authfile /tmp/ghcr-auth.json ghcr.io/${{ github.repository }}:${{ inputs.ushift-branch }}-${{ inputs.okd-version-tag }}
          sudo podman push --authfile /tmp/ghcr-auth.json ghcr.io/${{ github.repository }}:latest

          # Prepare the release note for the bootc image usage
          TAG=${{ inputs.ushift-branch }}-${{ inputs.okd-version-tag }} envsubst < .github/workflows/release.md > /tmp/release.md

      - name: Add release note for bootc image usage
        if: contains(fromJSON('["all", "bootc-image"]'), inputs.build)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.ushift-branch }}-${{ inputs.okd-version-tag }}
          body_path: /tmp/release.md
